# Generated by Django 6.0 on 2026-04-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
